import type { SceneBlueprint } from './types.js';

export const sceneBlueprints: SceneBlueprint[] = [
  { id: 'promise-proof-lock', title: 'Promise, proof, lock', roles: ['hook', 'launch'], energy: 'energetic', duration: [4, 8], phases: [{ name: 'promise', range: [0, 0.25], purpose: 'State one sharp promise.', recipes: ['kinetic-slam'] }, { name: 'proof', range: [0.2, 0.72], purpose: 'Reveal the product or mechanism that earns the promise.', recipes: ['camera-push', 'cursor-confirm'] }, { name: 'lock', range: [0.7, 1], purpose: 'Resolve on the brand or outcome.', recipes: ['scale-lock'] }], slots: ['promise', 'proofAsset', 'outcome', 'brand'], signatureMove: 'The promise physically hands its accent shape into the proof frame.', constraints: ['One claim only.', 'Proof must be observed or sourced.'] },
  { id: 'detail-to-system', title: 'Detail to system', roles: ['platform', 'architecture', 'workflow'], energy: 'cinematic', duration: [5, 10], phases: [{ name: 'detail', range: [0, 0.25], purpose: 'Establish one meaningful detail.', recipes: ['focus-rack'] }, { name: 'reveal', range: [0.2, 0.75], purpose: 'Pull back to reveal the surrounding system.', recipes: ['camera-pull', 'panel-stack'] }, { name: 'map', range: [0.7, 1], purpose: 'Connect components into a readable whole.', recipes: ['line-route'] }], slots: ['detail', 'systemParts', 'relationshipLabels'], signatureMove: 'One detail stays anchored while the rest of the system unfolds around it.', constraints: ['No perspective text below readable size.', 'Every system part needs a real role.'] },
  { id: 'action-result', title: 'Action and result', roles: ['product-proof', 'walkthrough'], energy: 'balanced', duration: [4, 9], phases: [{ name: 'orient', range: [0, 0.22], purpose: 'Show where the action occurs.', recipes: ['camera-push'] }, { name: 'act', range: [0.2, 0.52], purpose: 'Perform one real interaction.', recipes: ['cursor-confirm'] }, { name: 'observe', range: [0.5, 0.82], purpose: 'Let the visible result appear.', recipes: ['masked-rise'] }, { name: 'confirm', range: [0.8, 1], purpose: 'Summarize the consequence.', recipes: ['scale-lock'] }], slots: ['productSurface', 'action', 'result', 'caption'], signatureMove: 'The cursor yields immediately to the resulting product state.', constraints: ['Never simulate an unobserved product result.', 'Keep the result visible for at least 1.2 seconds.'] },
  { id: 'evidence-chain', title: 'Evidence chain', roles: ['proof', 'case-study', 'analysis'], energy: 'restrained', duration: [6, 12], phases: [{ name: 'source', range: [0, 0.3], purpose: 'Present unaltered evidence.', recipes: ['editorial-wipe'] }, { name: 'inspect', range: [0.25, 0.7], purpose: 'Direct attention to the relevant detail.', recipes: ['scan-reveal', 'camera-push'] }, { name: 'conclude', range: [0.68, 1], purpose: 'State the supported finding.', recipes: ['masked-rise'] }], slots: ['evidenceAsset', 'annotation', 'finding', 'source'], signatureMove: 'A source annotation becomes the underline beneath the finding.', constraints: ['Retain provenance.', 'Do not visually alter the meaning of evidence.'] },
  { id: 'metric-journey', title: 'Metric journey', roles: ['growth', 'metric', 'insight'], energy: 'cinematic', duration: [5, 10], phases: [{ name: 'context', range: [0, 0.28], purpose: 'Establish the baseline.', recipes: ['line-route'] }, { name: 'journey', range: [0.2, 0.72], purpose: 'Travel through the data progression.', recipes: ['path-follow'] }, { name: 'resolve', range: [0.68, 1], purpose: 'Lock the final value and meaning.', recipes: ['metric-count', 'focus-rack'] }], slots: ['dataset', 'baseline', 'finalValue', 'meaning'], signatureMove: 'The moving data marker becomes the decimal point or accent of the final metric.', constraints: ['Geometry must derive from real values.', 'State units and time range.'] },
  { id: 'comparison-decision', title: 'Comparison decision', roles: ['comparison', 'before-after', 'differentiation'], energy: 'balanced', duration: [5, 9], phases: [{ name: 'establish', range: [0, 0.3], purpose: 'Introduce both sides fairly.', recipes: ['split-reveal'] }, { name: 'contrast', range: [0.25, 0.72], purpose: 'Reveal the meaningful differences.', recipes: ['list-stagger'] }, { name: 'decision', range: [0.7, 1], purpose: 'Resolve on the resulting choice or outcome.', recipes: ['scale-lock'] }], slots: ['left', 'right', 'criteria', 'outcome'], signatureMove: 'The divider becomes a check or directional mark at resolution.', constraints: ['Use the same measurement basis on both sides.', 'Keep both labels visible.'] },
  { id: 'modular-ecosystem', title: 'Modular ecosystem', roles: ['features', 'integrations', 'platform'], energy: 'balanced', duration: [6, 11], phases: [{ name: 'core', range: [0, 0.22], purpose: 'Establish the primary platform capability.', recipes: ['scale-lock'] }, { name: 'modules', range: [0.18, 0.7], purpose: 'Assemble supporting capabilities by importance.', recipes: ['depth-assemble', 'panel-stack'] }, { name: 'connect', range: [0.65, 1], purpose: 'Show how the system works together.', recipes: ['line-route', 'orbit-settle'] }], slots: ['core', 'modules', 'relationships', 'outcome'], signatureMove: 'Module edges extend into the relationship routes.', constraints: ['Module size follows importance.', 'Avoid equal card grids.'] },
  { id: 'manifesto-release', title: 'Manifesto release', roles: ['launch', 'brand', 'outro'], energy: 'energetic', duration: [4, 8], phases: [{ name: 'verbs', range: [0, 0.55], purpose: 'Build energy through short semantic beats.', recipes: ['kinetic-slam', 'word-cascade'] }, { name: 'silence', range: [0.52, 0.68], purpose: 'Create a brief contrast hold.', recipes: ['hard-register-cut'] }, { name: 'release', range: [0.65, 1], purpose: 'Resolve on the product and CTA.', recipes: ['depth-assemble', 'scale-lock'] }], slots: ['verbs', 'productName', 'cta'], signatureMove: 'The final verb fragments assemble into the brand mark.', constraints: ['No more than five verb beats.', 'Final CTA remains static for at least one second.'] },
];
