import { createHash, randomUUID } from 'node:crypto';
import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { z } from 'zod';

const hash = z.string().regex(/^[a-f0-9]{64}$/);
const sourceSchema = z.object({ id: z.string().min(1).max(200), text: z.string().max(20000), tags: z.array(z.string().max(100)).max(100).default([]), available: z.boolean().default(true) }).strict();
export const semanticIndexSchema = z.object({ version: z.literal(1), id: hash, createdAt: z.string().datetime(), algorithm: z.literal('local-tfidf-v1'), model: z.object({ id: z.string(), version: z.string(), localPath: z.string().optional(), sha256: hash.optional() }).strict(), documents: z.array(z.object({ id: z.string(), terms: z.record(z.string(), z.number().finite().positive()), norm: z.number().finite().nonnegative(), available: z.boolean() }).strict()).max(100000) }).strict();
function terms(text: string): string[] { const words = text.toLocaleLowerCase().match(/[\p{L}\p{N}]+/gu) ?? []; return [...words, ...words.flatMap(word => word.length > 3 ? Array.from({ length: word.length - 2 }, (_, index) => `#${word.slice(index, index + 3)}`) : [])]; }
function contentId(payload: Omit<z.infer<typeof semanticIndexSchema>, 'id'>): string { return createHash('sha256').update(JSON.stringify(payload)).digest('hex'); }
async function fileHash(file: string): Promise<string> { return createHash('sha256').update(await readFile(file)).digest('hex'); }
export async function buildSemanticIndex(raw: z.input<typeof sourceSchema>[], options: { model?: { id: string; version: string; localPath: string; sha256: string } } = {}) {
  const sources = z.array(sourceSchema).max(100000).parse(raw), counts = new Map<string, number>(); for (const source of sources) for (const term of new Set(terms(`${source.id} ${source.tags.join(' ')} ${source.text}`))) counts.set(term, (counts.get(term) ?? 0) + 1);
  const documents = sources.map(source => { const frequencies = new Map<string, number>(); for (const term of terms(`${source.id} ${source.tags.join(' ')} ${source.text}`)) frequencies.set(term, (frequencies.get(term) ?? 0) + 1); const weighted = Object.fromEntries([...frequencies].map(([term, frequency]) => [term, frequency * Math.log((sources.length + 1) / ((counts.get(term) ?? 0) + 1)) + frequency])); return { id: source.id, terms: weighted, norm: Math.sqrt(Object.values(weighted).reduce((sum, value) => sum + value ** 2, 0)), available: source.available }; });
  const model = options.model ? { id: options.model.id, version: options.model.version, localPath: path.resolve(options.model.localPath), sha256: options.model.sha256 } : { id: 'builtin-sparse', version: '1' }; if (options.model && await fileHash(model.localPath!) !== model.sha256) throw new Error('Pinned semantic model bytes do not match the declared hash');
  const payload = { version: 1 as const, createdAt: new Date().toISOString(), algorithm: 'local-tfidf-v1' as const, model, documents }; return semanticIndexSchema.parse({ id: contentId(payload), ...payload });
}
export function searchSemanticIndex(index: z.infer<typeof semanticIndexSchema>, query: string, limit = 20) { const parsed = semanticIndexSchema.parse(index), queryTerms = terms(z.string().min(1).max(2000).parse(query)), frequencies = new Map<string, number>(); for (const term of queryTerms) frequencies.set(term, (frequencies.get(term) ?? 0) + 1); const norm = Math.sqrt([...frequencies.values()].reduce((sum, value) => sum + value ** 2, 0)); const ranked = parsed.documents.map(document => ({ id: document.id, available: document.available, score: norm && document.norm ? [...frequencies].reduce((sum, [term, value]) => sum + value * (document.terms[term] ?? 0), 0) / norm / document.norm : 0 })).filter(item => item.score > 0).sort((a, b) => b.score - a.score || a.id.localeCompare(b.id)); const unavailable = ranked.filter(item => !item.available).map(item => item.id); return { version: 1 as const, answeringTier: 'local-semantic' as const, algorithm: parsed.algorithm, model: parsed.model, indexId: parsed.id, offline: true as const, results: ranked.filter(item => item.available).slice(0, z.number().int().min(1).max(100).parse(limit)), unavailable, queryRetention: 'none' as const }; }
export function auditSemanticIndex(index: z.infer<typeof semanticIndexSchema>, registryIds: string[]) { const indexed = new Set(index.documents.map(item => item.id)), registry = new Set(registryIds); return { missingFromIndex: registryIds.filter(id => !indexed.has(id)), missingFromRegistry: index.documents.map(item => item.id).filter(id => !registry.has(id)), unavailable: index.documents.filter(item => !item.available).map(item => item.id), inSync: registryIds.every(id => indexed.has(id)) && index.documents.every(item => registry.has(item.id)) }; }
export async function refreshSemanticIndex(file: string, sources: z.input<typeof sourceSchema>[], options: Parameters<typeof buildSemanticIndex>[1] = {}) { const index = await buildSemanticIndex(sources, options), target = path.resolve(file), temporary = `${target}.${randomUUID()}.tmp`; await mkdir(path.dirname(target), { recursive: true }); await writeFile(temporary, `${JSON.stringify(index)}\n`, { flag: 'wx' }); await rename(temporary, target); return index; }
