import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { z } from 'zod';

const surfaceSchema = z.object({ sdk: z.string().min(1), cli: z.string().min(1), mcp: z.string().min(1), studio: z.string().min(1), skill: z.string().min(1) }).strict();
export const capabilityContractSchema = z.object({
  id: z.string().regex(/^[a-z][a-z0-9-]*$/), title: z.string().min(1), summary: z.string().min(1),
  inputSchema: z.record(z.string(), z.unknown()), outputSchema: z.record(z.string(), z.unknown()), example: z.record(z.string(), z.unknown()), surfaces: surfaceSchema,
}).strict();
export type CapabilityContract = z.infer<typeof capabilityContractSchema>;
const object = (properties: Record<string, unknown>, required: string[] = []) => ({ type: 'object', properties, required, additionalProperties: false });
const string = { type: 'string' }, positive = { type: 'number', exclusiveMinimum: 0 };
export const capabilityContracts: CapabilityContract[] = [
  { id: 'validate', title: 'Validate project', summary: 'Validate Creative IR, assets, layout, timing and delivery constraints.', inputSchema: object({ project: string, strict: { type: 'boolean' } }, ['project']), outputSchema: object({ findings: { type: 'array' } }, ['findings']), example: { project: './project', strict: true }, surfaces: { sdk: 'validateProject', cli: "command('validate')", mcp: "'genmotion_validate'", studio: "'/api/check-report'", skill: 'genmotion validate' } },
  { id: 'frame', title: 'Render native frame', summary: 'Evaluate one exact native frame without browser composition.', inputSchema: object({ project: string, at: { type: 'number', minimum: 0 }, output: string }, ['project', 'at', 'output']), outputSchema: object({ output: string, frame: { type: 'number' } }, ['output', 'frame']), example: { project: './project', at: 1.5, output: './frame.png' }, surfaces: { sdk: 'renderFramePng', cli: "command('frame')", mcp: "'genmotion_frame'", studio: "'/frame/:frame.png'", skill: 'representative native PNG frames' } },
  { id: 'render-plan', title: 'Plan deterministic render', summary: 'Freeze delivery options and dependency identities before work begins.', inputSchema: object({ project: string, quality: { enum: ['draft', 'standard', 'high'] }, codec: { enum: ['h264', 'h265', 'vp9', 'prores'] } }, ['project']), outputSchema: object({ sourceHash: string, dependencyHash: string, delivery: { type: 'object' } }, ['sourceHash', 'dependencyHash', 'delivery']), example: { project: './project', quality: 'high', codec: 'h264' }, surfaces: { sdk: 'createRenderPlan', cli: "command('render-plan')", mcp: "'genmotion_render_plan'", studio: "'/api/render-plan'", skill: 'render plan' } },
  { id: 'render', title: 'Render verified master', summary: 'Render, mix, encode, fully decode and attest a native master.', inputSchema: object({ project: string, output: string, quality: { enum: ['draft', 'standard', 'high'] }, deliveryPurpose: { enum: ['internal-review', 'reference-comparison', 'editorial', 'commercial', 'public'] } }, ['project', 'output']), outputSchema: object({ output: string, manifest: { type: 'object' } }, ['output', 'manifest']), example: { project: './project', output: './master.mp4', quality: 'high', deliveryPurpose: 'commercial' }, surfaces: { sdk: 'renderProject', cli: "command('render')", mcp: "'genmotion_render'", studio: "'/api/render'", skill: 'genmotion render' } },
  { id: 'catalog', title: 'Inspect catalog', summary: 'Search and describe native motion capabilities before applying them.', inputSchema: object({ query: string, limit: positive }), outputSchema: object({ results: { type: 'array' } }, ['results']), example: { query: 'editorial title', limit: 8 }, surfaces: { sdk: 'searchCatalog', cli: "command('catalog')", mcp: "'genmotion_catalog'", studio: 'catalog: { motions', skill: 'catalog' } },
  { id: 'project-edit', title: 'Commit semantic edit', summary: 'Apply one revision-safe validated Creative IR transaction.', inputSchema: object({ project: string, expectedRevision: string, edits: { type: 'array' } }, ['project', 'expectedRevision', 'edits']), outputSchema: object({ revision: string }, ['revision']), example: { project: './project', expectedRevision: '0123456789abcdef'.repeat(4), edits: [] }, surfaces: { sdk: 'applySemanticEdits', cli: "command('edit')", mcp: "'genmotion_edit'", studio: "'/api/edit'", skill: 'transactional patches' } },
  { id: 'reference-adaptation', title: 'Inspect reference adaptation', summary: 'Inspect source, measurement, pixel-origin and native-target provenance.', inputSchema: object({ project: string }, ['project']), outputSchema: object({ report: { type: 'object' }, map: { type: 'object' } }, ['report', 'map']), example: { project: './project' }, surfaces: { sdk: 'inspectReferenceAdaptation', cli: 'reference-adaptation', mcp: 'reference_adaptation', studio: "'/api/reference-adaptation'", skill: 'reference adaptation' } },
  { id: 'upgrade', title: 'Upgrade project safely', summary: 'Inspect compatibility, preserve pins, migrate, validate native frames and retain rollback.', inputSchema: object({ project: string, actor: string, dryRun: { type: 'boolean' } }, ['project', 'actor']), outputSchema: object({ migrations: { type: 'array' }, representativeFrames: { type: 'array' }, backup: { type: ['string', 'null'] } }, ['migrations']), example: { project: './project', actor: 'release-manager', dryRun: true }, surfaces: { sdk: 'upgradeProject', cli: "command('upgrade')", mcp: "'genmotion_upgrade'", studio: "'/api/upgrade'", skill: 'upgrade report' } },
];

export interface CapabilityDrift { capability: string; surface: keyof CapabilityContract['surfaces']; marker: string; source: string }
const files: Record<keyof CapabilityContract['surfaces'], string> = { sdk: 'src/index.ts', cli: 'src/cli.ts', mcp: 'src/mcp.ts', studio: 'src/studio/server.ts', skill: 'skills/genmotion/SKILL.md' };
export async function auditCapabilityContracts(root: string): Promise<{ ok: boolean; contracts: number; drift: CapabilityDrift[] }> {
  const source = Object.fromEntries(await Promise.all(Object.entries(files).map(async ([surface, file]) => [surface, await readFile(path.join(root, file), 'utf8')])) as Array<[keyof typeof files, string]>);
  const drift: CapabilityDrift[] = [];
  for (const contract of capabilityContracts) for (const surface of Object.keys(files) as Array<keyof typeof files>) { const marker = contract.surfaces[surface], filename = files[surface]; if (!(source[surface] ?? '').includes(marker)) drift.push({ capability: contract.id, surface, marker, source: filename }); }
  return { ok: drift.length === 0, contracts: capabilityContracts.length, drift };
}
export function capabilityContractsMarkdown(): string { return `${['# Generated capability contracts', '', 'Generated from `src/capabilities/contracts.ts`. Do not edit this file directly.', '', ...capabilityContracts.flatMap(contract => [`## ${contract.title}`, '', contract.summary, '', `- ID: \`${contract.id}\``, `- SDK: \`${contract.surfaces.sdk}\``, `- CLI marker: \`${contract.surfaces.cli}\``, `- MCP marker: \`${contract.surfaces.mcp}\``, `- Studio marker: \`${contract.surfaces.studio}\``, `- Skill marker: \`${contract.surfaces.skill}\``, ''])].join('\n')}\n`; }
