import { createHash, randomUUID } from 'node:crypto';
import { createReadStream } from 'node:fs';
import { copyFile, link, mkdir, readdir, rm, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { z } from 'zod';
import { projectAssetReferences } from './asset-references.js';
import { resolveProjectAsset, type LoadedProject } from './loader.js';

const hashSchema = z.string().regex(/^[a-f0-9]{64}$/);
export interface ContentStoreOptions { maxBytes?: number; maxEntries?: number }
async function digest(file: string): Promise<{ hash: string; bytes: number }> { const hash = createHash('sha256'); let bytes = 0; for await (const chunk of createReadStream(file)) { bytes += (chunk as Buffer).length; hash.update(chunk as Buffer); } return { hash: hash.digest('hex'), bytes }; }
export class ContentStore {
  readonly root: string; readonly maxBytes: number; readonly maxEntries: number;
  constructor(root: string, options: ContentStoreOptions = {}) { this.root = path.resolve(root); this.maxBytes = z.number().int().positive().max(1024 ** 4).parse(options.maxBytes ?? 32 * 1024 ** 3); this.maxEntries = z.number().int().positive().max(100000).parse(options.maxEntries ?? 10000); }
  private file(hash: string): string { hashSchema.parse(hash); return path.join(this.root, hash.slice(0, 2), hash); }
  async inventory() { let bytes = 0; const entries: Array<{ hash: string; bytes: number }> = []; try { for (const shard of await readdir(this.root)) { const directory = path.join(this.root, shard); if (!(await stat(directory)).isDirectory()) continue; for (const name of await readdir(directory)) { if (!hashSchema.safeParse(name).success) continue; const size = (await stat(path.join(directory, name))).size; bytes += size; entries.push({ hash: name, bytes: size }); } } } catch (error) { if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error; } return { entries, bytes, maxBytes: this.maxBytes, maxEntries: this.maxEntries }; }
  async put(source: string) { const file = path.resolve(source), identity = await digest(file), target = this.file(identity.hash); try { const existing = await digest(target); if (existing.hash !== identity.hash || existing.bytes !== identity.bytes) throw new Error('Content store entry failed integrity verification'); return { ...identity, path: target, reused: true }; } catch (error) { if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error; }
    const inventory = await this.inventory(); if (inventory.entries.length + 1 > this.maxEntries || inventory.bytes + identity.bytes > this.maxBytes) throw new Error('Content store quota exceeded'); await mkdir(path.dirname(target), { recursive: true }); const temporary = `${target}.${randomUUID()}.tmp`; await copyFile(file, temporary); if ((await digest(temporary)).hash !== identity.hash) { await rm(temporary, { force: true }); throw new Error('Source changed while entering content store'); } try { await link(temporary, target); } catch (error) { if ((error as NodeJS.ErrnoException).code !== 'EEXIST') throw error; } finally { await rm(temporary, { force: true }); } return { ...identity, path: target, reused: false }; }
  async materialize(hash: string, destination: string) { const source = this.file(hash), actual = await digest(source); if (actual.hash !== hash) throw new Error('Content store entry is corrupt'); const target = path.resolve(destination); await mkdir(path.dirname(target), { recursive: true }); const temporary = `${target}.${randomUUID()}.tmp`; await copyFile(source, temporary); try { await link(temporary, target); } finally { await rm(temporary, { force: true }); } return { hash, bytes: actual.bytes, path: target }; }
  async putProject(loaded: LoadedProject) { const files = await Promise.all(projectAssetReferences(loaded.sourceProject).sort().map(async reference => ({ role: reference, ...(await this.put(resolveProjectAsset(loaded.projectDir, reference))) }))); const document = path.join(this.root, `.project-${randomUUID()}.json`); await mkdir(this.root, { recursive: true }); await writeFile(document, `${JSON.stringify(loaded.sourceProject, null, 2)}\n`); try { const project = await this.put(document); return { version: 1 as const, project, files, dependencyIdentity: createHash('sha256').update(JSON.stringify(files.map(file => [file.role, file.hash]))).digest('hex') }; } finally { await rm(document, { force: true }); } }
}
