import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { z } from 'zod';
import { GenmotionError } from '../errors.js';
import type { GenmotionProject } from './schema.js';
const hash = z.string().regex(/^[a-f0-9]{64}$/);
export const deliveryPurposeSchema = z.enum(['internal-review', 'reference-comparison', 'editorial', 'commercial', 'public']);
export const referenceSourceSchema = z.object({ id: z.string().min(1).max(200), path: z.string().min(1).max(4096), contentHash: hash, originalLocation: z.string().min(1).max(8192), rights: z.enum(['owned', 'licensed', 'unknown']), permittedUses: z.array(deliveryPurposeSchema).max(5), redistribution: z.enum(['allowed', 'prohibited', 'with-attribution']), attribution: z.string().max(4000).default(''), authorization: z.object({ actor: z.string().min(1), at: z.string().datetime(), basis: z.string().min(1).max(4000) }).strict().optional(), unresolvedRightsWarning: z.string().min(1).max(4000).optional() }).strict().superRefine((item, context) => { if (item.rights === 'unknown' && !item.unresolvedRightsWarning) context.addIssue({ code: 'custom', message: 'Unknown reference rights require a visible warning' }); if (item.rights !== 'unknown' && !item.authorization) context.addIssue({ code: 'custom', message: 'Known rights require the user authorization record' }); if (item.redistribution === 'with-attribution' && !item.attribution) context.addIssue({ code: 'custom', message: 'Attribution text is required' }); });
export const referenceSourcesSchema = z.array(referenceSourceSchema).max(1000).refine(items => new Set(items.map(item => item.id)).size === items.length, 'Reference source IDs must be unique');
export function assertReferenceExportAllowed(project: Pick<GenmotionProject, 'referenceSources'>, purpose: z.infer<typeof deliveryPurposeSchema>): void { for (const source of project.referenceSources) { if (source.rights === 'unknown') throw new GenmotionError('REFERENCE_RIGHTS_UNRESOLVED', `Reference ${source.id} has unresolved rights.`, { source: source.id, warning: source.unresolvedRightsWarning }); if (!source.permittedUses.includes(purpose)) throw new GenmotionError('REFERENCE_USE_RESTRICTED', `Reference ${source.id} does not permit ${purpose} export.`, { source: source.id, permittedUses: source.permittedUses }); if (source.redistribution === 'prohibited' && ['public', 'commercial'].includes(purpose)) throw new GenmotionError('REFERENCE_REDISTRIBUTION_RESTRICTED', `Reference ${source.id} prohibits redistributed exports.`, { source: source.id }); } }
export async function verifyFrozenReferenceSources(project: Pick<GenmotionProject, 'referenceSources'>, projectDirectory: string): Promise<void> { const { resolveProjectAsset } = await import('./loader.js'); for (const source of project.referenceSources) { let actual: string; try { actual = createHash('sha256').update(await readFile(resolveProjectAsset(projectDirectory, source.path))).digest('hex'); } catch (error) { if (error instanceof GenmotionError && error.code === 'ASSET_OUTSIDE_PROJECT') throw error; throw new GenmotionError('REFERENCE_SOURCE_MISSING', `Frozen reference ${source.id} is missing.`, { source: source.id, path: source.path, error }); } if (actual !== source.contentHash) throw new GenmotionError('REFERENCE_SOURCE_CHANGED', `Frozen reference ${source.id} does not match its recorded hash.`, { source: source.id, expected: source.contentHash, actual }); } }
