import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { z } from 'zod';
import { resolveProjectAsset } from './loader.js';
const hash = z.string().regex(/^[a-f0-9]{64}$/), point = z.number().finite().nonnegative();
const region = z.object({ x: z.number().finite().min(0).max(1), y: z.number().finite().min(0).max(1), width: z.number().finite().positive().max(1), height: z.number().finite().positive().max(1), reason: z.string().min(1).max(2000) }).strict().refine(item => item.x + item.width <= 1 && item.y + item.height <= 1, 'Region must remain inside normalized source bounds');
export const referencePreparationNodeSchema = z.object({ id: z.string().min(1).max(200), kind: z.enum(['raw', 'frame', 'audio-stream', 'crop', 'matte', 'clean-plate', 'measurement', 'generated-derivative']), path: z.string().min(1).max(2048), sha256: hash, parents: z.array(z.object({ id: z.string(), sha256: hash }).strict()).max(128), tool: z.object({ id: z.string().min(1), version: z.string().min(1), settings: z.record(z.string(), z.union([z.string(), z.number().finite(), z.boolean(), z.null()])).default({}) }).strict(), timeMap: z.array(z.object({ sourceStart: point, sourceEnd: point, outputStart: point, outputEnd: point }).strict().refine(span => span.sourceEnd > span.sourceStart && span.outputEnd > span.outputStart, 'Time spans must be positive')).max(10000), retainedRegions: z.array(region).max(1000), replacedRegions: z.array(region).max(1000) }).strict().superRefine((node, context) => { if (node.kind !== 'raw' && !node.parents.length) context.addIssue({ code: 'custom', message: 'Prepared nodes require a parent hash' }); if (node.kind === 'generated-derivative' && !node.replacedRegions.length) context.addIssue({ code: 'custom', message: 'Generated replacements must declare replaced regions' }); });
export const referencePreparationGraphSchema = z.object({ version: z.literal(1), referenceId: z.string().min(1), nodes: z.array(referencePreparationNodeSchema).max(10000) }).strict().superRefine((graph, context) => { const byId = new Map(graph.nodes.map(node => [node.id, node])); if (byId.size !== graph.nodes.length) context.addIssue({ code: 'custom', message: 'Preparation node IDs must be unique' }); for (const node of graph.nodes) for (const parent of node.parents) if (byId.get(parent.id)?.sha256 !== parent.sha256) context.addIssue({ code: 'custom', message: `Parent identity mismatch for ${node.id}` }); const visit = (id: string, trail: Set<string>): void => { if (trail.has(id)) { context.addIssue({ code: 'custom', message: 'Preparation graph contains a cycle' }); return; } const next = new Set(trail); next.add(id); for (const parent of byId.get(id)?.parents ?? []) visit(parent.id, next); }; for (const node of graph.nodes) visit(node.id, new Set()); });
export function addReferencePreparationNode(graph: z.infer<typeof referencePreparationGraphSchema>, node: z.input<typeof referencePreparationNodeSchema>) { return referencePreparationGraphSchema.parse({ ...graph, nodes: [...graph.nodes.filter(item => item.id !== node.id), node] }); }
export function removeReferencePreparationBranch(graph: z.infer<typeof referencePreparationGraphSchema>, id: string) { const removed = new Set([id]); let changed = true; while (changed) { changed = false; for (const node of graph.nodes) if (!removed.has(node.id) && node.parents.some(parent => removed.has(parent.id))) { removed.add(node.id); changed = true; } } return { graph: referencePreparationGraphSchema.parse({ ...graph, nodes: graph.nodes.filter(node => !removed.has(node.id)) }), removed: [...removed] }; }
export async function verifyReferencePreparation(graph: z.infer<typeof referencePreparationGraphSchema>, projectDirectory: string) { const checked = referencePreparationGraphSchema.parse(graph), findings: Array<{ code: string; nodeId: string; path: string }> = []; for (const node of checked.nodes) try { if (createHash('sha256').update(await readFile(resolveProjectAsset(projectDirectory, node.path))).digest('hex') !== node.sha256) findings.push({ code: 'REFERENCE_DERIVATIVE_CHANGED', nodeId: node.id, path: node.path }); } catch { findings.push({ code: 'REFERENCE_DERIVATIVE_MISSING', nodeId: node.id, path: node.path }); } return { ok: findings.length === 0, findings }; }
