export * from './errors.js';
export * from './ir/schema.js';
export * from './ir/brief.js';
export * from './ir/bundle.js';
export * from './ir/loader.js';
export * from './ir/store.js';
export * from './ir/track-locks.js';
export * from './ir/patch.js';
export * from './ir/edit.js';
export * from './ir/validate.js';
export * from './ir/review-sampling.js';
export * from './ir/review-artifact.js';
export * from './ir/render-plan.js';
export * from './ir/operation-diagnostic.js';
export * from './ir/check-report.js';
export * from './ir/acceptance-assertions.js';
export * from './ir/parameters.js';
export * from './ir/expressions.js';
export * from './ir/preflight.js';
export * from './ir/render-selection.js';
export * from './ir/automatic-duration.js';
export * from './ir/data-sources.js';
export * from './ir/authoring-schema.js';
export * from './ir/gesture-recording.js';
export * from './engine/gesture-recording.js';
export * from './engine/motion-diagnostics.js';
export * from './engine/variant-comparison.js';
export * from './engine/audio-intelligence.js';
export * from './engine/color-analysis.js';
export * from './ir/variants.js';
export * from './ir/easing-edits.js';
export * from './ir/compositions.js';
export * from './captions.js';
export * from './ir/caption-delivery.js';
export * from './ir/music-workflow.js';
export * from './ir/presentation.js';
export * from './ir/review-bundle.js';
export * from './engine/draw.js';
export * from './engine/assets.js';
export * from './engine/render.js';
export * from './engine/render-projection.js';
export * from './engine/render-view.js';
export * from './engine/alpha-output.js';
export * from './engine/output-compatibility.js';
export * from './engine/preview.js';
export * from './engine/motion.js';
export * from './engine/probe.js';
export * from './engine/path.js';
export * from './engine/svg-path.js';
export * from './engine/path-operations.js';
export * from './engine/path-editing.js';
export * from './engine/primitives.js';
export * from './ir/path-operations.js';
export * from './ir/audio-effects.js';
export * from './ir/audio-rack.js';
export * from './engine/audio-effects.js';
export * from './engine/audio.js';
export * from './engine/loudness.js';
export * from './engine/paint.js';
export * from './ir/paint.js';
export * from './engine/animation.js';
export * from './engine/kinematics.js';
export * from './engine/time.js';
export * from './engine/text-layout.js';
export * from './engine/text-measure.js';
export * from './engine/composition-time.js';
export * from './engine/interpolation.js';
export * from './engine/easing.js';
export * from './engine/procedural.js';
export * from './engine/constraints.js';
export * from './creative/types.js';
export * from './catalog/types.js';
export * from './catalog/motions.js';
export * from './catalog/references.js';
export * from './catalog/blueprints.js';
export * from './catalog/audit.js';
export * from './studio/server.js';
export * from './agent/runtime.js';
export * from './catalog/custom.js';
export * from './engine/effects.js';
export * from './engine/masks.js';
export * from './player.js';
export * from './ir/production.js';
export * from './ir/production-service.js';
export * from './ir/lut.js';
export * from './ir/lut-import.js';
export * from './engine/lut.js';
export * from './ir/markers.js';

export { warpCanvasQuad, quadHomography, projectPoint, perspectiveQuad, cubeTransitionQuads, type Quad } from './engine/projective.js';

export { analyzeAudioFile, audioSpectrum, analyzeOnsets, audioAnalysisOptionsSchema, type AudioAnalysis, type AudioAnalysisOptions, type WaveformLevel } from './engine/audio-analysis.js';

export { imageAnimationSchema, type ImageAnimation } from './ir/image-animation.js';
export { imageSourceFrame, spriteFrameRect } from './engine/image-animation.js';
export { projectAssetReferences } from './ir/asset-references.js';

export { mediaSourceCrop, mediaRoundedPath } from './engine/media-geometry.js';

export { editCaptions, paginateCaptions, captionEditSchema, captionPageOptionsSchema } from './ir/caption-editing.js';
export { captionWordRanges, captionLineRanges } from './engine/caption-layout.js';

export { nativeKernelSchema, inspectNativeKernel, type NativeKernel, type KernelExpression } from './ir/native-kernel.js';
export { runNativeKernel } from './engine/native-kernel.js';

export { inspectMedia, type MediaInfo, type MediaStreamInfo } from './engine/media-probe.js';

export { conformMedia, mediaConformPlan, mediaConformOptionsSchema, type MediaConformOptions } from './engine/media-conform.js';
export { EditingSession, filesystemEditingAdapter, memoryEditingAdapter, editingCheckpointSchema, type EditingAdapter, type EditingSnapshot, type EditingWriteOptions, type EditingWriteResult, type EditingReceipt, type EditingDispatchReceipt, type EditingFailureReceipt, type EditingEvent, type EditingCheckpoint, type EditingSessionOptions, type SessionApplyOptions } from './ir/session.js';
export { editingCommandSchema, executeEditingCommand, type EditingCommand } from './ir/session.js';
export { instanceOverridesSchema, instanceOverrideChangeSchema, type InstanceOverrides, type InstanceOverrideChange } from './ir/schema.js';
export { inspectInstancePath, applyDirectInstanceOverrides, overridePropertyValue, overrideHash } from './ir/instance-overrides.js';
export { materializeCompositionInstance } from './ir/materialize.js';
export { documentDiff } from './ir/document-diff.js';
export { reconcileProjects, reconciliationResolutionSchema, type ReconciliationResolution, type ReconciliationConflict, type ReconciliationResult } from './ir/reconcile.js';
export { queryEditingProject, editingQuerySchema, type EditingQuery } from './ir/query.js';
export { reviewInstanceOverrides, reconcileInstanceOverrides, instanceBaseRevision, overrideResolutionSchema, type OverrideReview, type OverrideDiagnostic, type OverrideResolution } from './ir/override-reconciliation.js';
export { readProjectSourceSnapshot, type ProjectSourceSnapshot } from './ir/store.js';
export { editingContextPatchSchema, editingContextView, updateEditingContext, initialEditingContext, type EditingContextPatch, type EditingContextState, type EditingContextView } from './ir/editing-context.js';
export { executeStudioCommand, studioBridgeCommandSchema, studioBridgePermissionsSchema, type StudioBridgeCommand, type StudioBridgePermissions } from './studio/bridge.js';
export { namedCheckpointSchema, filesystemCheckpointStore, memoryCheckpointStore, makeNamedCheckpoint, type NamedCheckpointStore, type NamedCheckpoint, type CheckpointSummary } from './ir/checkpoints.js';
export { textDirection, textWrapUnits, revealUnicodeText } from './engine/text-unicode.js';
export { studioCommands, normalizeShortcut, resolvedShortcuts, studioShortcutsSchema, type StudioCommandId } from './studio/commands.js';
export { pathNodeEditSchema, pathEditStateSchema, type PathNodeEdit, type PathEditState } from './ir/path-nodes.js';
export { inspectPathNodes, editPathNodes, serializePathNodes, pathRevision, type EditablePathNode, type EditablePathContour, type PathNodeMode } from './engine/path-nodes.js';
